apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: ../kafka
    repoURL: https://github.com/dminnikov/infra.git
    targetRevision: HEAD