apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: nginx
    repoURL: https://github.com/dminnikov/infra  # note: the oci:// syntax is not included.
    targetRevision: HEAD
    helm:
      valueFiles:
      - /nginx/values.yaml
  destination:
    namespace: dev
    server: https://kubernetes.default.svc