apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 15.9.0
    helm:
      valueFiles:
      - $values/values/nginx-values.yaml
  - repoURL: 'https://github.com/dminnikov/infra.git'
    targetRevision: HEAD
    ref: values
  destination:
    namespace: dev
    server: https://kubernetes.default.svc