apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 15.9.0
    helm:
      valueFiles:
      - https://github.com/dminnikov/infra/blob/main/values/nginx-values.yaml
  destination:
    namespace: dev
    server: https://kubernetes.default.svc