apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev-stands2h6t
  source:
    repoURL: https://github.com/dminnikov/infra
    chart: postgresql
    targetRevision: HEAD