apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-prod
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-options: Force=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/dminnikov/infra
    path: apache
    targetRevision: release_2
    helm:
      valueFiles:
      - values-prod.yaml
  syncPolicy:
    automated: {}