apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  annotations:
    # С помощью этого параметра указываем порядок создания
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  # Обратите внимание на namespace – он должен быть argocd
  namespace: argocd
spec:
  destination:
    # А вот тут уже неймспейс, куда будет устанавливаться сам чарт
    namespace: postgresql
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    # Указываем путь до чарта
    path: charts/postgresql
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # Обратите внимание, что путь до зашифрованных
    # values мы указываем в новом формате
    # secrets+age-import://<key-volume-mount>/<key-name>.txt?<relative/path/to/the/encrypted/secrets.yaml>
    helm:
      valueFiles:
        - ./values.yaml
  syncPolicy:
    automated: {}