apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solr-stage
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/dminnikov/infra
    path: solr
    targetRevision: release_1
    helm:
      valueFiles:
      - values-stage.yaml
  syncPolicy:
    automated: {}